### ISSUE TITLE
求助： 可以帮忙完善一下README.md 文档么。

### ISSUE THREAD

**Issue by lei1996** [pheihuihui/huobi-mini-app#1]
我clone 了项目下来，npm start &&   buiild 了client 之后需要 额外启动web 容器么？

**Comment by pheihuihui** [comment]
> 我clone 了项目下来，npm start && buiild 了client 之后需要 额外启动web 容器么？

client我还没开始做，打算部到github pages上。（server是部署在azure上的。) FYI
